#!/bin/bash

UBUNTU=$( cat /etc/*-release | grep -i Ubuntu )
FEDORA=$( cat /etc/*-release | grep -i Fedora )
CENTOS=$( cat /etc/*-release | grep -i CentOS )

if [ "$1" == '-y' ]; then
    NOINTMODE='yes'
fi

# Clean packages caches
if [[ $UBUNTU ]]; then
    apt-get clean
    apt-get -y autoremove
fi
if [[ $FEDORA  || $CENTOS ]]; then
    yum clean all
fi

# Delete /etc/resolv.conf
#rm -f /etc/resolv.conf

# Clean command history
rm -f /root/.bash_history
rm -f /home/*/.bash_history

# Clean ssh data
rm -f /root/.ssh/authorized_keys /root/.ssh/known_hosts
rm -f /home/*/.ssh/authorized_keys /home/*/.ssh/known_hosts

# Delete udev net rules files:
rm -f /etc/udev/rules.d/70-persistent-net.rules

# Delete VNXACE log
rm -f /var/log/vnxaced.log

# Delete logs
sudo rm -f /var/log/*.gz
for i in {1..9}; do rm -f /var/log/*.$i; done
sudo rm -f /var/crash/*

# Recreate swap file full of zeros
sudo swapoff /swap.img
sudo dd if=/dev/zero of=/swap.img bs=1M count=1024
sudo chmod 600 /swap.img
sudo mkswap /swap.img
sudo swapon /swap.img

if [ ! $NOINTMODE ]; then
    while true; do
        # Ask for a message to save in /etc/vnx_rootfs_version file
        echo    "** Save a log message in /etc/vnx_rootfs_version file "
        echo -n "** describing the modifications done? "
        read -n 1 -p "[y/n] " answer
        echo ""
        case $answer in
            [Yy]* )
                    echo "** Log message (1 line maximum):"
                    read logmsg
                    DATE=`date`
                    echo "MODDATE=$DATE" >> /etc/vnx_rootfs_version
                    echo "MODDESC=$logmsg" >> /etc/vnx_rootfs_version
                    break;;
            [Nn]* ) break;;
            * )     echo "** Error: please answer 'y' or 'n'.";;
        esac
    done
fi

# Check whether we are running chrooted or not
if [ ! -e /proc/1/root ]; then
  # Probably running chrooted. Do not halt!
  echo "**"
  echo "** Cannot read /proc. Probably running chrooted. Not halting"
  echo "** Type 'exit' to exit from chroot"
  exit
elif [ ! -e /proc/1/root -o "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
  # We are chrooted! Do not halt
  echo "**"
  echo "** Running chrooted. Not halting"
  echo "** Type 'exit' to exit from chroot"
  exit
fi

# We are NOT chrooted! We halt the virtual machine
#halt -p
